MegEngine/mgeconvert

- mgeconvert/mge_context/mge_op.py
> fix(mge_op): fix initialization of ConvolutionBackwardDataOpr

- ci/pytest_caffe_and_onnx.sh
- ci/pytest_cambricon.sh
- mgeconvert/mge_context/mge_utils.py
- setup.py
- test/utils.py
@lixiangyin666 @xpmemeda please kindly review.
> Support megengine 1.2

- MANIFEST.in
- README.md
- mgeconvert/caffe_converter/caffe_converter.py
- mgeconvert/caffe_converter/caffe_op.py
- mgeconvert/mge_context/mge_net.py
- mgeconvert/mge_context/mge_op.py
- mgeconvert/mge_context/mge_utils.py
- mgeconvert/onnx_converter/onnx_converter.py
- mgeconvert/onnx_converter/onnx_op.py
- mgeconvert/utils/convert_caffe.py
- mgeconvert/utils/convert_onnx.py
- mgeconvert/version.py
- test/test_caffe.py
- test/test_onnx.py
- test/utils.py
@lixiangyin666 @xpmemeda  please kindly review, thanks!
> support more operators

- mgeconvert/caffe_converter/caffe_op.py
- mgeconvert/mge_context/mge_op.py
- mgeconvert/mge_context/mge_tensor.py
- mgeconvert/onnx_converter/onnx_op.py
- mgeconvert/version.py
- test/test_caffe.py
- test/utils.py
* caffe layer的top name用输出var的名字而不是用opr的名字
*  用同样的策略修改了tensor的名字，如替换:,.
> feat(caffe/tensor): change caffe top name and replace tensor name use the same method with opr name

- .gitignore
- mgeconvert/caffe_converter/caffe_op.py
- tools/change_batch.py
- tools/convert_and_check.py
- fix caffe elemwise top name issue
- fix reshape NNIE mistake warning
- add caffe/onnx convert and check tools
> Fix caffe top name and add some convert tools

- mgeconvert/caffe_converter/caffe_converter.py
- mgeconvert/caffe_converter/caffe_op.py
- mgeconvert/mge_context/mge_op.py
- test/utils.py
修改caffe转换带bias的Conv和FC的问题
- 增加pattern match匹配conv/deconv + add并转换到caffe的带bias的Convolution层
- 增加pattern match匹配matrimul + add并转换到caffe的带bias的FC层
> fix(caffe): fix caffe convolution and fullconnected bias convert issue

- ci/pytest_caffe_and_onnx.sh
- ci/pytest_cambricon.sh
- ci/pytest_tflite.sh
CI 中添加 MegEngine 1.3.1 测试
@lixiangyin666 @yzchen
> feat(mgeconvert): support megengine v1.3.1

- mgeconvert/tflite_converter/tflite_converter.py
- mgeconvert/tflite_converter/tflite_op.py
- test/test_tflite.py
- test/utils.py
> fix(tflite_converter):fix tflite ConvTranspose2d

- mgeconvert/mge_context/mge_transform.py
@yzchen @daisycx pls kindly review.
> fix(mge_transform): the number of output operators may be greater than one

- .github/workflows/ci.yml
- mgeconvert/mge_context/mge_transform.py
- test/test_transform.py
- test/utils.py
修改原因：tflite需要把激活函数吸收到前一个op
@yzchen @daisycx
> fix(mge_transform): consider activation when fusing op

- README.md
- mgeconvert/mge_context/mge_op.py
- mgeconvert/mge_context/mge_transform.py
- mgeconvert/tflite_converter/tflite_converter.py
- mgeconvert/tflite_converter/tflite_op.py
- test/test_tflite.py
@yzchen @lixiangyin666 
求 review。
> feat(tflite_converter): add slice op

- mgeconvert/mge_context/mge_op.py
- mgeconvert/onnx_converter/onnx_op.py
- mgeconvert/version.py
- test/test_onnx.py
修复 onnx conv 转换， please kindly review @dc3671
> fix(onnx_converter): fix conv converter of onnx

- bin/convert
修traced module和mge转换器接口不一致的bug
> fix converter interface param

- README.md
- bin/convert
- mgeconvert/converter_ir/ir_graph.py
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/mge_to_caffe.py
- mgeconvert/converters/mge_to_onnx.py
- mgeconvert/converters/mge_to_tflite.py
- mgeconvert/converters/tm_to_caffe.py
- mgeconvert/converters/tm_to_onnx.py
- mgeconvert/converters/tm_to_tflite.py
- mgeconvert/frontend/tm_to_ir/op_generators/__init__.py
- mgeconvert/frontend/tm_to_ir/op_generators/batchnorm.py
- mgeconvert/frontend/tm_to_ir/op_generators/concat.py
- mgeconvert/frontend/tm_to_ir/op_generators/conv_bn2d.py
- mgeconvert/frontend/tm_to_ir/op_generators/elemwise.py
- mgeconvert/frontend/tm_to_ir/op_generators/matmul.py
- mgeconvert/frontend/tm_to_ir/op_generators/pooling.py
- mgeconvert/frontend/tm_to_ir/op_generators/resize.py
- mgeconvert/frontend/tm_to_ir/op_generators/softmax.py
- mgeconvert/frontend/tm_to_ir/tm_frontend.py
- mgeconvert/frontend/tm_to_ir/tm_tensor_resolver.py
- test/mge/test_tflite.py
- test/traced_module/test_caffe.py
- test/traced_module/test_onnx.py
- test/traced_module/test_qat_tflite.py
- test/traced_module/test_tflite.py
- test/utils.py
commit 1：resolve MGE-3328，支持ConvRelu、ConvBn、ConvBnRelu及相应的QAT module 转到各个后端
commit 2：resolve MGE-3315，TracedModule转换器支持指定end point，完善接口的注释
> support ConvRelu ConvBn ConvBnRelu

- mgeconvert/converters/tm_to_tflite.py
- mgeconvert/frontend/tm_to_ir/qat_pattern.py
resolve MGE-3346
增加QAT deconv bias的pattern match
> add-qat-deconv-bias-pattern

- README.md
- bin/convert
- mgeconvert/backend/ir_to_caffe/caffe_converter.py
- mgeconvert/backend/ir_to_caffe/caffe_op.py
- mgeconvert/backend/ir_to_onnx/onnx_op.py
- mgeconvert/converter_ir/ir_graph.py
- mgeconvert/converter_ir/ir_quantizer.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/mge_to_caffe.py
- mgeconvert/converters/tm_to_caffe.py
- mgeconvert/converters/tm_to_onnx.py
- mgeconvert/converters/tm_to_tflite.py
- mgeconvert/frontend/tm_to_ir/op_generators/resize.py
- test/traced_module/test_caffe.py
- test/traced_module/test_onnx.py
- test/traced_module/test_qat_caffe.py
- test/utils.py
1. add support for caffe dump quantize info 
2. add support for onnx op like resize
3. add bash complete  resovle MGE-2525
> add caffe quantize

- bin/convert
> fix(mgeconvert/bash): fix bash complete error

- bin/convert
1. split complete script when set spesific target
> split complete target

- ci/pytest_caffe_and_onnx.sh
- mgeconvert/backend/ir_to_caffe/init.sh
1. support caffe use different protoversion 
resolve MGE-3397
> fix(mgeconvert/caffe): fix caffe protobuf version

- mgeconvert/backend/ir_to_caffe/caffe_op.py
1. fix layer name != blob name
> fix(convert/caffe): fix bn layer name error

- ci/pytest_caffe_and_onnx.sh
- mgeconvert/backend/ir_to_onnx/init.sh
- mgeconvert/backend/ir_to_onnx/onnx_converter.py
- mgeconvert/backend/ir_to_onnx/onnx_op.py
- mgeconvert/converters/tm_to_onnx.py
> Onnx quantizer

- README.md
- bin/convert
- mgeconvert/backend/ir_to_onnx/onnx_op.py
- mgeconvert/backend/ir_to_tflite/tflite_converter.py
- mgeconvert/converter_ir/ir_quantizer.py
- mgeconvert/converters/tm_to_caffe.py
- mgeconvert/converters/tm_to_onnx.py
- mgeconvert/converters/tm_to_tflite.py
- mgeconvert/frontend/tm_to_ir/tm_frontend.py
- test/traced_module/test_qat_caffe.py
- test/traced_module/test_qat_tflite.py
统一traced module转换器接口中 require_quantize 参数的语义
> unifrom-convert-interfaces

- bin/convert
- mgeconvert/frontend/tm_to_ir/tm_utils.py
> fix(convert): fix convert script

- bin/convert
- mgeconvert/backend/ir_to_caffe/caffe_converter.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/tm_to_caffe.py
- mgeconvert/frontend/tm_to_ir/tm_tensor_resolver.py
- mgeconvert/frontend/tm_to_ir/tm_utils.py
- test/traced_module/test_caffe.py
- test/utils.py
> feat(mgeconvert): support fuse linear/matmul bn

- README.md
- bin/convert
- ci/requires-style.txt
- ci/test_convert_cmd.sh
- mgeconvert/backend/ir_to_mge/__init__.py
- mgeconvert/backend/ir_to_mge/mge_converter.py
- mgeconvert/backend/ir_to_mge/mge_op.py
- mgeconvert/backend/ir_to_onnx/init.sh
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/converters/onnx_to_mge.py
- mgeconvert/converters/onnx_to_tm.py
- mgeconvert/frontend/onnx_to_ir/__init__.py
- mgeconvert/frontend/onnx_to_ir/onnx_frontend.py
- mgeconvert/frontend/onnx_to_ir/onnxproto_resolver.py
- mgeconvert/frontend/onnx_to_ir/op_generators/__init__.py
- mgeconvert/frontend/onnx_to_ir/op_generators/base.py
- mgeconvert/frontend/onnx_to_ir/op_generators/elemwise.py
- mgeconvert/frontend/onnx_to_ir/op_generators/nn.py
- mgeconvert/frontend/onnx_to_ir/op_generators/tensor.py
- setup.py
> add onnx to mge/tm convert

- bin/convert
- mgeconvert/backend/ir_to_tflite/tflite_op.py
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/converter_ir/ir_tensor.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/tm_to_tflite.py
- mgeconvert/frontend/tm_to_ir/op_generators/__init__.py
- mgeconvert/frontend/tm_to_ir/op_generators/pad.py
- mgeconvert/version.py
- test/traced_module/test_tflite.py
- test/utils.py
support pixelshuffle for tflite converter
> support pixelshuffle for tflite converter

- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/frontend/tm_to_ir/op_generators/conv_bn2d.py
- test/traced_module/test_tflite.py
- test/utils.py
resolve MGE-3572.
commit 1：修复EXPAND_CONVRELU 的 pass 中对输出节点的命名出错，导致 caffe 有重复 conv layer
commit 2：在 fuse bn 的相关函数中增加对 bias = None 的处理
> Fix expand convrelu pass

- bin/convert
- mgeconvert/backend/ir_to_caffe/caffe_op.py
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/tm_to_caffe.py
- mgeconvert/frontend/tm_to_ir/op_generators/conv_bn2d.py
- mgeconvert/frontend/tm_to_ir/op_generators/elemwise.py
- mgeconvert/frontend/tm_to_ir/tm_frontend.py
1. 修复部分复杂模型转换时报  maximum recursion depth exceeded 的问题
2. 支持fused_add_relu算子的转换
> fix(mgeconvert): support FuseAddRelu and fix some bugs

- mgeconvert/frontend/tm_to_ir/tm_tensor_resolver.py
> fix(frontend/tm): fix getting a tensor from module

- mgeconvert/backend/ir_to_mge/mge_op.py
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/converters/onnx_to_mge.py
- mgeconvert/frontend/onnx_to_ir/onnx_frontend.py
- mgeconvert/frontend/onnx_to_ir/op_generators/elemwise.py
- mgeconvert/frontend/onnx_to_ir/op_generators/nn.py
- mgeconvert/frontend/onnx_to_ir/op_generators/tensor.py
@dingshaohua960303 kindly review plz
> fix some bug and add support for Gather

- mgeconvert/backend/ir_to_onnx/onnx_op.py
- mgeconvert/converters/tm_to_onnx.py
- mgeconvert/frontend/tm_to_ir/op_generators/conv2d.py
- mgeconvert/frontend/tm_to_ir/op_generators/softmax.py
修复 onnx conerter 中 softmax 和 gemm 里的多余操作。
以及 concat op 不支持 axis < 0 的情况。
> fix softmax, gemm, concat op for onnx converter

- bin/convert
- ci/test_convert_cmd.sh
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/mge_to_tflite.py
- mgeconvert/converters/tm_to_tflite.py
resolve [MGE-3791](https://jira.megvii-inc.com/browse/MGE-3791)
tflite转换器增加 ``prefer_same_pad_mode`` 参数可设置 conv pad mode 优先选择SAME模式
> add tflite prefer_same_pad_mode option

- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/mge_to_caffe.py
- mgeconvert/converters/mge_to_onnx.py
- mgeconvert/converters/mge_to_tflite.py
- mgeconvert/frontend/mge_to_ir/op_generators/elemwise.py
- test/mge/test_caffe.py
- test/mge/test_onnx.py
- test/mge/test_tflite.py
resolve [MGE-3807](https://jira.megvii-inc.com/browse/MGE-3807)
增加处理 fuse_add_sigmoid 的transform
> add expand add-sigmoid transform

- .github/workflows/complete_unit_test.yaml
- ci/pytest_caffe_and_onnx_complete.sh
- ci/pytest_tflite_complete.sh
- ci/test.sh
- mgeconvert/backend/ir_to_onnx/onnx_op.py
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/frontend/mge_to_ir/op_generators/elemwise.py
- test/traced_module/test_tflite.py
- test/utils.py
增加MegEngine1.8里新增的SoftmaxForward算子的支持，升级单元测试脚本里的MegEngine版本
@dingshaohua960303 please review, thanks
> support SoftmaxForward op and update ci megengine version

- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/tm_to_tflite.py
帮忙看看第 2 个 commit
在转到 nhwc 时，Flatten(Linear) 后 Linear 的权重也得转到 nhwc。
> Fix reshape tflite

- MANIFEST.in
- ci/build_package.sh
- ci/pytest_tflite.sh
- ci/pytest_tflite_complete.sh
- ci/requires-test.txt
- mgeconvert/backend/ir_to_onnx/init.sh
- mgeconvert/backend/ir_to_onnx/onnx_converter.py
- mgeconvert/backend/ir_to_tflite/build_flatbuffer.sh
- mgeconvert/backend/ir_to_tflite/init.sh
- mgeconvert/backend/ir_to_tflite/pyflexbuffers/__init__.py
- setup.py
> support-pack-wheel

- README.md
- ci/pytest_caffe_and_onnx.sh
- ci/pytest_caffe_and_onnx_complete.sh
- ci/pytest_tflite.sh
- ci/pytest_tflite_complete.sh
- mgeconvert/backend/ir_to_caffe/init.sh
- mgeconvert/backend/ir_to_onnx/init.sh
- mgeconvert/backend/ir_to_tflite/init.sh
- setup.py
- test/mge/test_tflite.py
- test/traced_module/test_qat_tflite.py
- test/traced_module/test_tflite.py
> fix install in venv

- mgeconvert/version.py
- setup.py
> fix install in conda env

- mgeconvert/frontend/tm_to_ir/tm_tensor_resolver.py
> fix: cant get the valid shape form node

- mgeconvert/backend/ir_to_mge/mge_op.py
- mgeconvert/frontend/onnx_to_ir/op_generators/elemwise.py
> feat: onnx front and mge back add hardsigmoid transfer

- mgeconvert/version.py
- setup.py
> fix install with tfversion option

- README.md
- ci/requires-style.txt
- ci/requires-test.txt
- ci/test_convert_cmd.sh
- mgeconvert/converter_ir/ir_transform.py
- mgeconvert/converters/onnx_to_mge.py
- mgeconvert/frontend/onnx_to_ir/onnxproto_resolver.py
- mgeconvert/frontend/onnx_to_ir/op_generators/nn.py
- setup.py
- test/onnx_model/mobilenetv2.py
- test/onnx_model/resnet18.py
修复onnx前端tensor owner_opr被覆盖的问题  
增加基于convert_ir的pass, onnx2mge中让fc的weight为非trans模式
> feat: add fc no trans pass to onnx2mge

- mgeconvert/backend/ir_to_tflite/tflite_op.py
- mgeconvert/converter_ir/ir_transform.py
tflite转换器Pooling算子支持SAME padding mode
> enable tflite pooling use same pad mode

- mgeconvert/backend/ir_to_mge/mge_op.py
- mgeconvert/converter_ir/ir_op.py
- mgeconvert/frontend/onnx_to_ir/op_generators/nn.py
> feat: onnx2mge add ConvTranspose

- mgeconvert/converter_ir/ir_transform.py
- test/utils.py
修复使用了scale factor的resize转tflite报错的问题
> fix resize with scale factor for tflite converter

- .github/workflows/ci.yml
- ci/pytest_transform.sh
- mgeconvert/converter_ir/ir_tensor.py
- mgeconvert/converter_ir/ir_transform.py
- test/traced_module/test_transform.py
> fix(transform): fix fuse activation and remove identity

- README.md
- ci/requires-style.txt
- ci/requires-test.txt
- mgeconvert/backend/ir_to_onnx/init.sh
- mgeconvert/frontend/onnx_to_ir/op_generators/tensor.py
- setup.py
> Onnx2mge support matmul
